import { theme } from '@/styles/theme'
import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  headerContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: theme.spacing.xxl,
  },
  profileAvatar: {
    backgroundColor: theme.colors.onBackground + 'aa',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: theme.colors.primary,
  },
  ImageIcon: {
    position: 'absolute',
    top: 0,
    right: 0,
    transform: [{ rotate: '45deg' }],
    fontSize: theme.fontSize.xl,
    color: theme.colors.primary,
  },
  settingIcon: {
    position: 'absolute',
    right: theme.spacing.sm,
    top: theme.spacing.sm,
    fontSize: theme.fontSize.xxl,
    color: theme.colors.onBackground + 'cc',
    transform: [{ rotate: '90deg' }],
    shadowColor: theme.colors.onBackground,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  headerStatsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    borderRadius: theme.borderRadius.lg,
    gap: theme.spacing.sm,
    marginTop: theme.spacing.xl,
  },
  headerStats: {
    flexGrow: 1,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.xs,
    alignContent: 'center',
    alignItems: 'center',
    borderRadius: theme.borderRadius.md,
    borderWidth: 1,
    borderColor: theme.colors.onBackground,
    gap: theme.spacing.xs,
    shadowColor: theme.colors.onBackground,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  headerStatsIcon: {
    fontSize: 32,
  },
  bigBtnContainer: {
    width: '100%',
    marginTop: theme.spacing.lg,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'stretch',
    gap: theme.spacing.md,
  },
  bigBtn: {
    flexDirection: 'row',
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    padding: theme.spacing.lg,
    gap: theme.spacing.sm,
    borderRadius: theme.borderRadius.md,
    backgroundColor: theme.colors.onBackground,
    height: 120,
  },
  bigBtnText: {
    marginLeft: theme.spacing.sm,
    color: theme.colors.background,
  },
  bigBtnIcon: {
    fontSize: 64,
    color: theme.colors.primary,
  },
  addBtnContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.primary,
    borderRadius: theme.borderRadius.md,
    flexGrow: 1,
  },
  addBtnIcon: {
    fontSize: 32,
    color: theme.colors.background,
  },
})
